# Auto-generated by the multi-agent code review pipeline.
# Rewritten import target: solution → tests.agent_generated.test_test_test_app
from unittest.mock import MagicMock, patch
from flask import Flask
from tests.agent_generated.test_test_test_app import create_app, lookup_user, main

def test_create_app():
    """Test the creation of the Flask app."""
    app = create_app()
    assert isinstance(app, Flask)

def test_index_route():
    """Test the index route of the Flask app."""
    app = create_app()
    with app.test_client() as client:
        response = client.get('/')
        assert response.status_code == 200
        assert response.data.decode() == "multi-agent-demo-app v0.1.0\n"

def test_health_route():
    """Test the health route of the Flask app."""
    app = create_app()
    with app.test_client() as client:
        response = client.get('/health')
        assert response.status_code == 200
        data = response.get_json()
        assert data['status'] == 'ok'
        assert data['version'] == '0.1.0'
        assert isinstance(data['uptime_seconds'], float)

def test_lookup_user():
    """Test the lookup_user function with various cases."""
    with MagicMock() as mock_db_conn:
        mock_cursor = mock_db_conn.cursor.return_value
        mock_cursor.fetchall.return_value = [{'id': 1, 'username': 'testuser'}]

        # Normal behavior
        result = lookup_user(mock_db_conn, 'testuser')
        mock_cursor.execute.assert_called_once_with(
            "SELECT * FROM users WHERE username = %s", ('testuser',)
        )
        assert result == [{'id': 1, 'username': 'testuser'}]

        # Edge case: empty username
        mock_cursor.fetchall.return_value = []
        result = lookup_user(mock_db_conn, '')
        mock_cursor.execute.assert_called_with(
            "SELECT * FROM users WHERE username = %s", ('',)
        )
        assert result == []

        # Edge case: non-existent user
        mock_cursor.fetchall.return_value = []
        result = lookup_user(mock_db_conn, 'nonexistentuser')
        mock_cursor.execute.assert_called_with(
            "SELECT * FROM users WHERE username = %s", ('nonexistentuser',)
        )
        assert result == []

def test_main():
    """Test the main function to ensure it runs the app with the correct parameters."""
    with patch('tests.agent_generated.test_test_test_app.run') as mock_run:
        with patch('os.environ.get', return_value='8000'):
            main()
            mock_run.assert_called_once_with(host="0.0.0.0", port=8000, debug=False)