# Auto-generated by the multi-agent code review pipeline.
# Rewritten import target: solution → app
import pytest
from unittest.mock import MagicMock, patch
from flask import Flask
from app import create_app, lookup_user, main

def test_create_app():
    app = create_app()
    assert isinstance(app, Flask)

    with app.test_client() as client:
        # Test the index endpoint
        response = client.get("/")
        assert response.status_code == 200
        assert response.data.decode() == "multi-agent-demo-app v0.1.0\n"

        # Test the health endpoint
        response = client.get("/health")
        assert response.status_code == 200
        data = response.get_json()
        assert data["status"] == "ok"
        assert data["version"] == "0.1.0"
        assert "uptime_seconds" in data and isinstance(data["uptime_seconds"], (int, float))
        assert data["uptime_seconds"] >= 0

def test_lookup_user():
    mock_db_conn = MagicMock()
    mock_cursor = mock_db_conn.cursor.return_value.__enter__.return_value
    mock_cursor.fetchall.return_value = [("user1", "email1@example.com")]

    result = lookup_user(mock_db_conn, "user1")
    mock_cursor.execute.assert_called_once_with("SELECT * FROM users WHERE username = %s", ("user1",))
    assert result == [("user1", "email1@example.com")]

def test_main(monkeypatch):
    mock_run = MagicMock()
    monkeypatch.setattr("app.app.run", mock_run)

    with patch.dict("os.environ", {"PORT": "8000"}):
        main()
        mock_run.assert_called_once_with(host="0.0.0.0", port=8000, debug=False)