# Auto-generated by the multi-agent code review pipeline.
# Rewritten import target: solution → app
import pytest
from unittest.mock import patch
from flask.testing import FlaskClient
from app import create_app, main

@pytest.fixture
def client() -> FlaskClient:
    app = create_app()
    return app.test_client()

def test_index_endpoint(client: FlaskClient):
    response = client.get("/")
    assert response.status_code == 200
    assert response.data.decode() == "multi-agent-demo-app v0.1.0\n"

def test_health_endpoint(client: FlaskClient):
    with patch("app.time.monotonic") as mock_monotonic:
        mock_monotonic.return_value = 1000.0
        response = client.get("/health")
        assert response.status_code == 200
        data = response.get_json()
        assert data["status"] == "ok"
        assert data["version"] == "0.1.0"
        assert "uptime_seconds" in data and isinstance(data["uptime_seconds"], (int, float))
        assert 0.0 <= data["uptime_seconds"] < 1000.0

def test_main(monkeypatch):
    with patch("app.app.run") as mock_run:
        monkeypatch.setenv("PORT", "5000")
        main()
        mock_run.assert_called_once_with(host="0.0.0.0", port=5000, debug=False)